# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT
version: 2.1

environment:
  BASH_ENV: ~/.bashrc

aliases:
  - &restore-cache
    keys:
      - dependency-cache-{{ checksum "yarn.lock" }}

  - &save-cache
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - yarn.lock

  - &persist_to_workspace
    root: '.'
    paths:
      - "*"

defaults: &defaults
  docker:
    - image: circleci/node:14.18.0-browsers
  working_directory: /tmp/workspace

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Install Top Level Dependencies
          command: |
            echo "Node version is: $(node --version)"
            echo "Running top level install..."
            yarn install --frozen-lockfile --non-interactive
          no_output_timeout: 10m
      - run:
          name: Install Edge Dependencies
          command: |
            echo "Node version is: $(node --version)"
            echo "Running top level install..."
            pushd edge
            yarn install --frozen-lockfile --non-interactive
            popd
          no_output_timeout: 10m
      - save_cache: *save-cache
      #- persist_to_workspace: *persist_to_workspace

  build: &buildAnchor
    <<: *defaults
    steps:
      - checkout
      #- attach_workspace:
      #    at: /tmp/workspace
      - restore_cache: *restore-cache
      - run:
          name: Setup AWS key
          command: |
            echo "export AWS_ACCESS_KEY_ID=${!AWS_ACCESS_KEY_ID_ENV_VAR}" >> ${BASH_ENV}
            echo "export AWS_SECRET_ACCESS_KEY=${!AWS_SECRET_ACCESS_KEY_ENV_VAR}" >> ${BASH_ENV}
      - run:
          name: Install AWS Profile
          command: |
            echo "PROJECT_DIR=${PROJECT_DIR}"
            echo "Installing Profile '${AWS_PROFILE}'..."
            mkdir -p ~/.aws
            printf "[profile ${AWS_PROFILE}]\nregion=${AWS_REGION}\noutput=json" > ~/.aws/config
            printf "[${AWS_PROFILE}]\naws_access_key_id=${!AWS_ACCESS_KEY_ID_ENV_VAR}\naws_secret_access_key=${!AWS_SECRET_ACCESS_KEY_ENV_VAR}" > ~/.aws/credentials
            echo "export AWS_PROFILE=${AWS_PROFILE}" >> ${BASH_ENV}
      - run:
          name: Building Source
          command: |
            echo "Node version is: $(node --version)"
            echo "Running yarn build:${STAGE}..."
            yarn build:${STAGE}
          no_output_timeout: 10m
      - run:
          name: Build Edge
          command: |
            echo "Node version is: $(node --version)"
            echo "Running yarn build..."
            pushd edge
            yarn build
            popd
          no_output_timeout: 10m
      - run:
          name: Check License Headers
          command: |
            ./check-headers.sh
      - save_cache: *save-cache
      #- persist_to_workspace: *persist_to_workspace

  buildDev:
    <<: *buildAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_DEV
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_DEV
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: dev
      ROOT_DOMAIN: dev.communitybridge.org
      PRODUCT_DOMAIN: easycla.dev.communitybridge.org

  buildStaging:
    <<: *buildAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_STAGING
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_STAGING
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: staging
      ROOT_DOMAIN: staging.communitybridge.org
      PRODUCT_DOMAIN: easycla.staging.communitybridge.org

  buildProd:
    <<: *buildAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_PROD
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_PROD
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: prod
      ROOT_DOMAIN: communitybridge.org
      PRODUCT_DOMAIN: easycla.communitybridge.org

  lint:
    <<: *defaults
    steps:
      - checkout
      #- attach_workspace:
      #    at: /tmp/workspace
      - restore_cache: *restore-cache
      - run: yarn eslint

  deployFrontend: &deployFrontendAnchor
    <<: *defaults
    steps:
      - checkout
      #- attach_workspace:
      #    at: /tmp/workspace
      - restore_cache: *restore-cache
      - run:
          name: Setup AWS key
          command: |
            echo "export AWS_ACCESS_KEY_ID=${!AWS_ACCESS_KEY_ID_ENV_VAR}" >> ${BASH_ENV}
            echo "export AWS_SECRET_ACCESS_KEY=${!AWS_SECRET_ACCESS_KEY_ENV_VAR}" >> ${BASH_ENV}
      - run:
          name: Install AWS Profile
          command: |
            echo "PROJECT_DIR=${PROJECT_DIR}"
            echo "Installing Profile '${AWS_PROFILE}'..."
            mkdir -p ~/.aws
            printf "[profile ${AWS_PROFILE}]\nregion=${AWS_REGION}\noutput=json" > ~/.aws/config
            printf "[${AWS_PROFILE}]\naws_access_key_id=${!AWS_ACCESS_KEY_ID_ENV_VAR}\naws_secret_access_key=${!AWS_SECRET_ACCESS_KEY_ENV_VAR}" > ~/.aws/credentials
            echo "export AWS_PROFILE=${AWS_PROFILE}" >> ${BASH_ENV}
      - run:
          name: Building Source
          command: |
            echo "Node version is: $(node --version)"
            echo "Running yarn build:${STAGE}..."
            yarn build:${STAGE}
          no_output_timeout: 10m
      - run:
          name: Build Edge
          command: |
            echo "Node version is: $(node --version)"
            echo "Running yarn build..."
            pushd edge
            yarn build
            popd
          no_output_timeout: 10m
      - run:
          name: Deploy Cloudfront and LambdaEdge
          command: |
            echo "Running: yarn sls deploy --stage=\"${STAGE}\" --verbose"
            SLS_DEBUG=* yarn sls deploy --stage="${STAGE}" --verbose
      - run:
          name: Deploy Frontend Bucket
          command: |
            echo "Running: yarn sls client deploy --stage=\"${STAGE}\" --verbose"
            SLS_DEBUG=* yarn sls client deploy --stage="${STAGE}" --verbose
      - run:
          name: Invalidate Cache
          command: |
            echo "Running: yarn sls cloudfrontInvalidate --stage=\"${STAGE}\" --region=\"${AWS_REGION}\" "
            SLS_DEBUG=* yarn sls cloudfrontInvalidate --stage="${STAGE}" --region="${AWS_REGION}" --verbose

  deployContributorConsoleDev:
    <<: *deployFrontendAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_DEV
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_DEV
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: dev
      ROOT_DOMAIN: dev.communitybridge.org
      PRODUCT_DOMAIN: easycla.dev.communitybridge.org

  deployContributorConsoleStaging:
    <<: *deployFrontendAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_STAGING
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_STAGING
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: staging
      ROOT_DOMAIN: staging.communitybridge.org
      PRODUCT_DOMAIN: easycla.staging.communitybridge.org

  deployContributorConsoleProd:
    <<: *deployFrontendAnchor
    environment:
      AWS_ACCESS_KEY_ID_ENV_VAR: AWS_ACCESS_KEY_ID_PROD
      AWS_SECRET_ACCESS_KEY_ENV_VAR: AWS_SECRET_ACCESS_KEY_PROD
      AWS_PROFILE: easycla
      AWS_REGION: us-east-1
      STAGE: prod
      ROOT_DOMAIN: communitybridge.org
      PRODUCT_DOMAIN: easycla.communitybridge.org


workflows:
  build_and_deploy:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - buildDev:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - buildDev
          filters:
            tags:
              only: /.*/
      - deployContributorConsoleDev:
          requires:
            - buildDev
            - lint
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - main

      # Deploy Staging
      - buildStaging:
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - approveStaging:
          type: approval
          requires:
            - buildStaging
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - deployContributorConsoleStaging:
          requires:
            - approveStaging
            - buildStaging
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

      # Deploy Prod
      - buildProd:
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - approveProd:
          type: approval
          requires:
            - deployContributorConsoleStaging
            - buildProd
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - deployContributorConsoleProd:
          requires:
            - approveProd
            - buildProd
          filters:
            branches:
              ignore: /.*/
            tags:
              # see semver examples https://regex101.com/r/Ly7O1x/201/
              only: /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
